// vite-prj/vue-001/src/views/Sample01.vue


<script setup>
    import { useCounterStore } from "../stores/storeCounter";
    const countStore = useCounterStore();

    defineProps({
        countValue: Number,
    })

    const emits = defineEmits([
        'incrementChild', 
        'decrementChild',
    ]);

    const increment = () => {
        emits('incrementChild','');
    };

    const decrement = () => {
        emits('decrementChild','');
    };
</script>

<template>
    <h1>Sample01</h1>
    <hr />
    <div>
        <button @click="increment">UP</button> &nbsp; 
            COUNT :: {{countValue}} &nbsp;
        <button @click="decrement">Down</button> &nbsp; 
    </div>
    <div>
        <button @click="countStore.incrementStore">Store Increment</button>
            STORE COUNT :: {{countStore.storeCounter}} &nbsp; 
        <button @click="countStore.decrementStore">Store Decrement</button>
    </div>

</template>

<style scoped>
</style>

// vite-prj/react-001/src/views/sample01.jsx

import React from "react";
import { useSelector, useDispatch } from "react-redux";
import { incrementByAmount, incrementStore, decrementStore } from "../stores/storeCounter";

const Sample01 = ({countValue, changeUp, changeDown}) => {

    const storeCount = useSelector((state) => state.counter.value);
    const dispatch = useDispatch();


    const increment = () => {
        changeUp();
    }

    const decrement = () => {
        changeDown();
    }


    return (
        <>
            <h1>Sample01</h1>
            <hr />
            <div>
                <button onClick={increment}>UP</button> &nbsp; 
                COUNT :: {countValue} &nbsp;
                <button onClick={decrement}>Down</button>
            </div>
            <div>
                <button onClick={() => dispatch(incrementStore())}>Store Increment</button>
                STORE COUNT :: {storeCount} &nbsp; 
                <button onClick={() => dispatch(decrementStore())}>Store Decrement</button>
            </div>

        </>
    );
}

export default Sample01;
